Repository NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC, pull requests merged in 2024-12, with the labels that each got.

#103 Close param_file for issue 102
  generic_tracers/cobalt_param_doc.F90
  generic_tracers/generic_COBALT.F90
Labels: bug

#105 consolidate user_add_params
  generic_tracers/cobalt_param_doc.F90
  generic_tracers/generic_COBALT.F90
Labels: CodeCleanUp

#106 additional parameter cleanup
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
Labels: documentation, CodeCleanUp
