Repository NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC, pull requests merged in 2024-06, with the labels that each got.

#66 Clean up and simplify bacterial production
  generic_tracers/cobalt_reg_diag.F90
  generic_tracers/cobalt_send_diag.F90
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
Labels: CodeCleanUp

#67 cleaned up plankton foodweb code
  generic_tracers/cobalt_reg_diag.F90
  generic_tracers/cobalt_send_diag.F90
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
Labels: documentation, CodeCleanUp

#69 added comments to the phytoplankton mortality section
  generic_tracers/generic_COBALT.F90
Labels: documentation, CodeCleanUp

#72 Simplify and clean up co2 calculation code
  generic_tracers/FMS_co2calc.F90
  generic_tracers/FMS_ocmip2_co2calc.F90.archive
  generic_tracers/generic_BLING.F90
  generic_tracers/generic_COBALT.F90
  generic_tracers/generic_abiotic.F90
  generic_tracers/generic_tracer.F90
Labels: enhancement, CodeCleanUp
