Repository NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC, pull requests merged in 2024-07, with the labels that each got.

#73 cleaned up burial and organic matter remin, added options to toggle/scale burial
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
Labels: documentation, enhancement, CodeCleanUp

#78 Remove vertdiff_M routines and make vertdiff_G just vertdiff
  generic_tracers/generic_tracer.F90
  generic_tracers/generic_tracer_utils.F90
Labels: CodeCleanUp

#79 Ballast and remin/clean code
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
Labels: documentation, CodeCleanUp
