Repository NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC, pull requests merged in 2024-04, with the labels that each got.

#31 added felim to diazo iron limitation
  generic_tracers/generic_COBALT.F90
Labels: CodeCleanUp

#32 Cleanup: float index and unused variables
  generic_tracers/generic_COBALT.F90
Labels: CodeCleanUp

#33 Make geolat and eqn_of_state as required
  generic_tracers/generic_COBALT.F90
  generic_tracers/generic_tracer.F90
Labels: enhancement

#39 Clean up of the light and phytoplankton growth calculations
  .github/ref/OM4.single_column.COBALT.p4/docker-linux-gnu/ocean.stats
  generic_tracers/generic_COBALT.F90
Labels: CodeCleanUp

#23 Eliminate repeated diagnostic ID checks and refactor send_diag section
  generic_tracers/cobalt_send_diag.F90
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
Labels: CodeCleanUp

#40 Generic cobalt id cleanup and remove legacy natu
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
Labels: CodeCleanUp

#46 Change COBALT bottom fluxes from 3d array to 2d
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
  generic_tracers/generic_tracer_utils.F90
Labels: CodeCleanUp

#43 New module for diagnostic registration
  generic_tracers/cobalt_reg_diag.F90
  generic_tracers/cobalt_send_diag.F90
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
Labels: CodeCleanUp

#45 Output COBALT runtime parameters to stdout
  generic_tracers/generic_COBALT.F90
  generic_tracers/generic_tracer_utils.F90
Labels: enhancement

#51 Refactor github actions CI workflow
  .github/ref/OM4.single_column.COBALT.p4/docker-linux-gnu/ocean.stats
  .github/workflows/cobalt_ci.yml
Labels: enhancement

#44 Remove ERGOM, TOPAZ, and miniBLING modules
  generic_tracers/generic_ERGOM.F90.archive
  generic_tracers/generic_TOPAZ.F90.archive
  generic_tracers/generic_miniBLING.F90.archive
  generic_tracers/generic_tracer.F90
Labels: CodeCleanUp

#53 V3 overview/clean code
  generic_tracers/generic_COBALT.F90
Labels: documentation
