Repository NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC, pull requests merged in 2024-09, with the labels that each got.

#93 added parameter definitions for phytoplankton growth + cleanup
  generic_tracers/cobalt_types.F90
  generic_tracers/generic_COBALT.F90
Labels: documentation, CodeCleanUp

#95 Update ocean.stats to resolve broken C
  .github/ref/OM4.single_column.COBALT.p4/docker-linux-gnu/ocean.stats
Labels: bug

#96 changed fe_2_n parameters so defaults were entered as Fe:N and not Fe:C
  generic_tracers/generic_COBALT.F90
Labels: CodeCleanUp
